# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "coa-op-scraper"
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Don Cruse"]
  s.date = "2013-03-26"
  s.description = "A scraper for intermediate appellate opinions"
  s.email = "doncruse@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "coa-op-scraper.gemspec",
    "lib/coa-op-scraper.rb",
    "lib/coa_docket_no.rb",
    "lib/legacy.rb",
    "lib/tames.rb",
    "spec/scrapers/legacy_scraper_spec.rb",
    "spec/scrapers/main_spec.rb",
    "spec/scrapers/tames_scraper_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/vcr.rb",
    "spec/vcr/legacy/02-2003-02-20.json",
    "spec/vcr/legacy/03-2013-01-10.json",
    "spec/vcr/tames/01-2012-01-19.json",
    "spec/vcr/tames/12-2003-01-31.json",
    "spec/vcr/tames/14-2005-01-20.json"
  ]
  s.homepage = "http://github.com/doncruse/coa-op-scraper"
  s.licenses = ["(c)2013 Don Cruse"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "A scraper for intermediate Texas appellate opinions"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

